name: Test Manual Workflow

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: false
        default: 'hello'
        type: string

jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test step
        run: |
          echo "Test workflow triggered manually!"
          echo "Input value: ${{ inputs.test_input }}"
          echo "✅ Manual workflow is working!"
